version: 0.2

phases:
  install:
    commands:
      - echo "Installing semgrep.."
      - pip install semgrep
  build:
    commands:
      - echo "Generaging timestamp..."
      - export TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
      #- echo "Semgrep logging..."
      #- semgrep login --token $SEMGREP_API_TOKEN
      - echo "Running Semgrep scan..."
      - semgrep ci --json --config=auto > semgrep_results_$TIMESTAMP.json
      - echo "Uploading Semgrep results to S3..."
      - aws s3 cp semgrep_results_$TIMESTAMP.json s3://build-artifacts-scp/semgrep_results_$TIMESTAMP.json

