version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Semgrep and AWS CLI..."
      - pip install semgrep awscli #semgrep, aws cli 설치

  build:
    commands:
      - echo "Running Semgrep scan..."
      - semgrep --config=auto --json > semgrep_results.json
      - echo "Uploading Semgrep results to S3..."
      - aws s3 cp semgrep_results.json s3://build-artifacts-scp/semgrep_results.json

